site_name: "Curriculum Vitae Valentin de Craene"
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode clair
  user_color_mode_toggle: true
  color_mode: auto

nav:
  - Curriculum Vitae: index.md
  - Portfolio: portfolio.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - admonition
  - tables

repo_url: https://valentindecraene.github.io
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.univ-lille.fr/valentin.de-craene/cycle_hn_meshs_2025
    - icon: material/web
      link: https://valentindecraene.github.io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/valentin-de-craene-189765221/
    - icon: material/email
      link: mailto:valentin.de-craene@univ-lille.fr
  copyright:
    text: "Valentin de Craene"
