site_name: "Curriculum Vitae Valentin de Craene"
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode clair
  user_color_mode_toggle: true
  color_mode: auto

nav:
  - Curriculum Vitae: index.md
  - Portfolio: portfolio.md
  - Publications: publications.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - tables

repo_url: https://github.com/ValentinDeCraene/valentindecraene.github.io
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.huma-num.fr/vdecraene
    - icon: fontawesome/brands/github
      link: https://github.com/ValentinDeCraene
    - icon: material/web
      link: https://valentindecraene.github.io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/valentin-de-craene-189765221/
    - icon: material/email
      link: mailto:valentin.de-craene@univ-lille.fr
      
copyright: Valentin de Craene - 2025
